name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  prettier:
    name: "prettier"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.45.3]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile

      - name: run prettier checker
        run: yarn prettier:check

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
